// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/pkg/proto/gophkeeper.proto

package gophkeeperpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecretType int32

const (
	SecretType_EMPTY       SecretType = 0
	SecretType_UNSPECIFIED SecretType = 1
	SecretType_CREDENTIALS SecretType = 2
	SecretType_TEXT        SecretType = 3
	SecretType_BINARY      SecretType = 4
	SecretType_CARD        SecretType = 5
)

// Enum value maps for SecretType.
var (
	SecretType_name = map[int32]string{
		0: "EMPTY",
		1: "UNSPECIFIED",
		2: "CREDENTIALS",
		3: "TEXT",
		4: "BINARY",
		5: "CARD",
	}
	SecretType_value = map[string]int32{
		"EMPTY":       0,
		"UNSPECIFIED": 1,
		"CREDENTIALS": 2,
		"TEXT":        3,
		"BINARY":      4,
		"CARD":        5,
	}
)

func (x SecretType) Enum() *SecretType {
	p := new(SecretType)
	*p = x
	return p
}

func (x SecretType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SecretType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pkg_proto_gophkeeper_proto_enumTypes[0].Descriptor()
}

func (SecretType) Type() protoreflect.EnumType {
	return &file_internal_pkg_proto_gophkeeper_proto_enumTypes[0]
}

func (x SecretType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SecretType.Descriptor instead.
func (SecretType) EnumDescriptor() ([]byte, []int) {
	return file_internal_pkg_proto_gophkeeper_proto_rawDescGZIP(), []int{0}
}

type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_gophkeeper_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUserRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *RegisterUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponse) ProtoMessage() {}

func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_gophkeeper_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_gophkeeper_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_gophkeeper_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Secret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          SecretType             `protobuf:"varint,2,opt,name=type,proto3,enum=gophkeeperpb.SecretType" json:"type,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Version       int32                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_gophkeeper_proto_rawDescGZIP(), []int{4}
}

func (x *Secret) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Secret) GetType() SecretType {
	if x != nil {
		return x.Type
	}
	return SecretType_EMPTY
}

func (x *Secret) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Secret) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Secret) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Secret) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	LocalSecrets  []*Secret              `protobuf:"bytes,2,rep,name=local_secrets,json=localSecrets,proto3" json:"local_secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_gophkeeper_proto_rawDescGZIP(), []int{5}
}

func (x *SyncRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SyncRequest) GetLocalSecrets() []*Secret {
	if x != nil {
		return x.LocalSecrets
	}
	return nil
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerSecrets []*Secret              `protobuf:"bytes,1,rep,name=server_secrets,json=serverSecrets,proto3" json:"server_secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_gophkeeper_proto_rawDescGZIP(), []int{6}
}

func (x *SyncResponse) GetServerSecrets() []*Secret {
	if x != nil {
		return x.ServerSecrets
	}
	return nil
}

type GetSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	SecretId      string                 `protobuf:"bytes,2,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_gophkeeper_proto_rawDescGZIP(), []int{7}
}

func (x *GetSecretRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetSecretRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

type GetSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        *Secret                `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretResponse) Reset() {
	*x = GetSecretResponse{}
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretResponse) ProtoMessage() {}

func (x *GetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_proto_gophkeeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretResponse.ProtoReflect.Descriptor instead.
func (*GetSecretResponse) Descriptor() ([]byte, []int) {
	return file_internal_pkg_proto_gophkeeper_proto_rawDescGZIP(), []int{8}
}

func (x *GetSecretResponse) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

var File_internal_pkg_proto_gophkeeper_proto protoreflect.FileDescriptor

const file_internal_pkg_proto_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"#internal/pkg/proto/gophkeeper.proto\x12\fgophkeeperpb\x1a\x1fgoogle/protobuf/timestamp.proto\"G\n" +
	"\x13RegisterUserRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"/\n" +
	"\x14RegisterUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\">\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xac\x02\n" +
	"\x06Secret\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.gophkeeperpb.SecretTypeR\x04type\x12>\n" +
	"\bmetadata\x18\x03 \x03(\v2\".gophkeeperpb.secret.MetadataEntryR\bmetadata\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x05R\aversion\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"^\n" +
	"\vSyncRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x129\n" +
	"\rlocal_secrets\x18\x02 \x03(\v2\x14.gophkeeperpb.SecretR\flocalSecrets\"K\n" +
	"\fSyncResponse\x12;\n" +
	"\x0eserver_secrets\x18\x01 \x03(\v2\x14.gophkeeperpb.SecretR\rserverSecrets\"E\n" +
	"\x10GetSecretRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tsecret_id\x18\x02 \x01(\tR\bsecretId\"A\n" +
	"\x11GetSecretResponse\x12,\n" +
	"\x06secret\x18\x01 \x01(\v2\x14.gophkeeperpb.SecretR\x06secret*Y\n" +
	"\n" +
	"SecretType\x12\t\n" +
	"\x05EMPTY\x10\x00\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x01\x12\x0f\n" +
	"\vCREDENTIALS\x10\x02\x12\b\n" +
	"\x04TEXT\x10\x03\x12\n" +
	"\n" +
	"\x06BINARY\x10\x04\x12\b\n" +
	"\x04CARD\x10\x052\xb2\x02\n" +
	"\n" +
	"GophKeeper\x12U\n" +
	"\fRegisterUser\x12!.gophkeeperpb.RegisterUserRequest\x1a\".gophkeeperpb.RegisterUserResponse\x12@\n" +
	"\x05Login\x12\x1a.gophkeeperpb.LoginRequest\x1a\x1b.gophkeeperpb.LoginResponse\x12=\n" +
	"\x04Sync\x12\x19.gophkeeperpb.SyncRequest\x1a\x1a.gophkeeperpb.SyncResponse\x12L\n" +
	"\tGetSecret\x12\x1e.gophkeeperpb.GetSecretRequest\x1a\x1f.gophkeeperpb.GetSecretResponseB!Z\x1finternal/pkg/proto/gophkeeperpbb\x06proto3"

var (
	file_internal_pkg_proto_gophkeeper_proto_rawDescOnce sync.Once
	file_internal_pkg_proto_gophkeeper_proto_rawDescData []byte
)

func file_internal_pkg_proto_gophkeeper_proto_rawDescGZIP() []byte {
	file_internal_pkg_proto_gophkeeper_proto_rawDescOnce.Do(func() {
		file_internal_pkg_proto_gophkeeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pkg_proto_gophkeeper_proto_rawDesc), len(file_internal_pkg_proto_gophkeeper_proto_rawDesc)))
	})
	return file_internal_pkg_proto_gophkeeper_proto_rawDescData
}

var file_internal_pkg_proto_gophkeeper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_pkg_proto_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_pkg_proto_gophkeeper_proto_goTypes = []any{
	(SecretType)(0),               // 0: gophkeeperpb.SecretType
	(*RegisterUserRequest)(nil),   // 1: gophkeeperpb.RegisterUserRequest
	(*RegisterUserResponse)(nil),  // 2: gophkeeperpb.RegisterUserResponse
	(*LoginRequest)(nil),          // 3: gophkeeperpb.LoginRequest
	(*LoginResponse)(nil),         // 4: gophkeeperpb.LoginResponse
	(*Secret)(nil),                // 5: gophkeeperpb.secret
	(*SyncRequest)(nil),           // 6: gophkeeperpb.SyncRequest
	(*SyncResponse)(nil),          // 7: gophkeeperpb.SyncResponse
	(*GetSecretRequest)(nil),      // 8: gophkeeperpb.GetSecretRequest
	(*GetSecretResponse)(nil),     // 9: gophkeeperpb.GetSecretResponse
	nil,                           // 10: gophkeeperpb.secret.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_internal_pkg_proto_gophkeeper_proto_depIdxs = []int32{
	0,  // 0: gophkeeperpb.secret.type:type_name -> gophkeeperpb.SecretType
	10, // 1: gophkeeperpb.secret.metadata:type_name -> gophkeeperpb.secret.MetadataEntry
	11, // 2: gophkeeperpb.secret.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 3: gophkeeperpb.SyncRequest.local_secrets:type_name -> gophkeeperpb.secret
	5,  // 4: gophkeeperpb.SyncResponse.server_secrets:type_name -> gophkeeperpb.secret
	5,  // 5: gophkeeperpb.GetSecretResponse.secret:type_name -> gophkeeperpb.secret
	1,  // 6: gophkeeperpb.GophKeeper.RegisterUser:input_type -> gophkeeperpb.RegisterUserRequest
	3,  // 7: gophkeeperpb.GophKeeper.Register:input_type -> gophkeeperpb.LoginRequest
	6,  // 8: gophkeeperpb.GophKeeper.Sync:input_type -> gophkeeperpb.SyncRequest
	8,  // 9: gophkeeperpb.GophKeeper.GetSecret:input_type -> gophkeeperpb.GetSecretRequest
	2,  // 10: gophkeeperpb.GophKeeper.RegisterUser:output_type -> gophkeeperpb.RegisterUserResponse
	4,  // 11: gophkeeperpb.GophKeeper.Register:output_type -> gophkeeperpb.LoginResponse
	7,  // 12: gophkeeperpb.GophKeeper.Sync:output_type -> gophkeeperpb.SyncResponse
	9,  // 13: gophkeeperpb.GophKeeper.GetSecret:output_type -> gophkeeperpb.GetSecretResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_internal_pkg_proto_gophkeeper_proto_init() }
func file_internal_pkg_proto_gophkeeper_proto_init() {
	if File_internal_pkg_proto_gophkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pkg_proto_gophkeeper_proto_rawDesc), len(file_internal_pkg_proto_gophkeeper_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pkg_proto_gophkeeper_proto_goTypes,
		DependencyIndexes: file_internal_pkg_proto_gophkeeper_proto_depIdxs,
		EnumInfos:         file_internal_pkg_proto_gophkeeper_proto_enumTypes,
		MessageInfos:      file_internal_pkg_proto_gophkeeper_proto_msgTypes,
	}.Build()
	File_internal_pkg_proto_gophkeeper_proto = out.File
	file_internal_pkg_proto_gophkeeper_proto_goTypes = nil
	file_internal_pkg_proto_gophkeeper_proto_depIdxs = nil
}
